### ISSUE TITLE
Build out redesigned New Work website

### ISSUE THREAD

**Issue by awesomephant** [Peace-Research-Institute-Frankfurt/websites#199]
- Design: https://xd.adobe.com/view/8106bfa4-58e1-4264-ae0d-e46735f46f06-d455/screen/83cf6490-65f9-4163-88b6-71e5d477da1d
- Staging: https://deploy-preview-201--leibniz-nw.netlify.app

## Todo

- [x] `<Tabs/>`
- [x] `<table/>`
- [x] `<Figure/>`
- [x] Byline
- [x] Download section (probs custom component)
- [x] Repeat post overview at the bottom of the post view
- [x] Differentiate standfirst and `h2` (probs in the sans and smaller type size)
- [x] Adjust index view copy: Longer, and it should explain the three categories (maybe with coloured markers)
- [x] Index view pills: More padding
- [x] #242
- [x] #241 
- [x] Add logo
- [x] Add placeholder illustrations
- [x] #243
- [x] #244
- [x] Update favicon
- [x] #245
- [x] #253
- [x] Refine callout typography

## Dates
- Prototype presentation (Neu bei Leibniz): 19 October
