### ISSUE TITLE
Build PRIF Review

### ISSUE THREAD

**Issue by awesomephant** [Peace-Research-Institute-Frankfurt/websites#210]
Staging: https://prif-review.netlify.app/

## Todo
- [ ] Build components
  - [ ] `<Map/>`
    - [x] ~~Base layer (continent outlines)~~
    - [x] Countries layer
    - [x] PRIF Network layer 
    - [ ] Set up responsive scaling
    - [ ] Add colours for connection types
  - [x] Markdown tables
  - [x] Further reading / aside component
  - [x] Responsive org chart
  - [x] Work out a rational way to do a person/bio component
  - [x] `<Callout />` (import from eLearning)
  - [x] Stacked bar chart component for discrete distributions
  - [x] Big Number component
  - [x] #225
  - [x] #223
- [x] Build views 
  - [x] Report
  - [x] Index
  - [x] Page
  - [x] Post
- [x] Misc
    - [x] TraCe Lines 
    - [x] Add frontmatter field for thumbnail
    - [x] #219
    - [x] #224
    - [ ] #226
